### ISSUE TITLE
使用lofterSpider的时候，运行3中途出现

### ISSUE THREAD

**Issue by Jreen** [akimitsukimiya/lofterSpider#3]
Traceback (most recent call last):
  File "/Users/jreen/lofterSpider-master/run.py", line 101, in <module>
    main()
  File "/Users/jreen/lofterSpider-master/run.py", line 37, in main
    spider.packPostsPlain(ptype = spiders.IMAGE)
  File "/Users/jreen/lofterSpider-master/spider.py", line 1133, in packPostsPlain
    posts = self.filterPosts(posts, ptype = ptype)
  File "/Users/jreen/lofterSpider-master/spider.py", line 1209, in filterPosts
    posts = [p for p in posts \
  File "/Users/jreen/lofterSpider-master/spider.py", line 1210, in <listcomp>
    if self.tagName in p.tag \
TypeError: argument of type 'NoneType' is not iterable

请问怎么解决？谢谢

**Comment by Jreen** [comment]
另外还出现另外一个问题：

DB ERROR: (sqlite3.IntegrityError) UNIQUE constraint failed: posts.id
[SQL: INSERT INTO posts (id, "blogId", "publisherUserId", "collectionId", title, "publishTime", "modifyTime", tag, type, digest, content, hot, permalink) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ((7616556309, 509053270, 509053270, 1124406,（后面应该是标签 tag,三段数字。文章标题，）
(Background on this error at: http://sqlalche.me/e/13/gkpj)
